import sqlite3
import json

conn = sqlite3.connect("database.sqlite")

cursor = conn.cursor()

# TURN ON FOREIGN KEY CONSTRAINTS
cursor.execute("PRAGMA foreign_keys = ON")

# insert into skillVideos
delete_query = """DELETE FROM skillVideos WHERE 1"""
cursor.execute(delete_query)
insert_skillVideos_query = """
INSERT INTO 
    skillVideos (id, contributor_id, title, link, is_full_recipe_video)
VALUES
    (0, 0, "How to Make Boiled Water", "watch?v=7_j5S38m3wY", 0),
    (1, 1, "One-Pan Scruffy Veg Lasagne", "ynYyM7NiPj0", 1),
    (2, 2, "How to Cook Perfect Quinoa", "watch?v=czVXWq_qCyk", 0),
    (3, 3, "Mastering Knife Skills - Dicing Technique", "watch?v=veE0E79dEEc", 0),
    -- GastroLabFood youtube channel
    (4, 4, "How to Cook Button Mushrooms", "watch?v=NpCtLNmp_nw", 0),
    (5, 5, "How to Poach an Egg", "watch?v=mth4vZBWiMY", 0),
    (6, 6, "How to Clean Shrimps", "watch?v=TPaekJ8Itf0", 0),
    (7, 7, "How to Clean Squid", "watch?v=bw0M8wYsyRM", 0),
    (8, 8, "How to Cut Leeks", "watch?v=VyvmBcg8KmY", 0),
    (9, 0, "How to Prepare Asparagus", "watch?v=N66jT42VWFw", 0),
    (10, 0, "How to Cut Shallots", "watch?v=JL02Lx-9GPk", 0),
    (11, 0, "How to Peel Garlic", "watch?v=tzV28_eGC0Q", 0),
    (12, 0, "How to Cook Scallops", "watch?v=ZZiFjt_ZPIc", 0),
    (13, 0, "How to Deseed a Pomegranate", "watch?v=1AMijG8RwEk", 0),
    (14, 0, "How to Parboil Tomatoes", "watch?v=30bwbsB1_cM", 0),
    (15, 0, "How to Separate An Egg White from the Yolk", "watch?v=daGhiEmcLSw", 0),
    (16, 0, "How to Fillet Fish - Way 1", "watch?v=q_DJYPYYenU", 0),
    (17, 0, "How to Saute Vegetables", "watch?v=aw_rqgMkzOw", 0),
    (18, 0, "How to Fillet Fish - Way 2", "watch?v=l7_lf937CIM", 0),
    (19, 0, "How to Reduce the Bitterness of Eggplants", "watch?v=4H6Qrgkk2e8", 0),
    (20, 0, "How to Make Flavoured Melted Butter", "watch?v=cpkZ3cMSbn0", 0),
    (21, 0, "How to Boil Brocolli", "watch?v=QoJdKkJbDRU", 0),
    (22, 0, "How to Dry Lettuce", "watch?v=HmsnPa9f0kc", 0),
    (23, 0, "How to Peel and Cut Oranges", "watch?v=LuLEJmu_heI", 0),
    (24, 0, "How to Prepare Dried Mushrooms", "watch?v=dyMYOkHviEY", 0),
    (25, 0, "How to Make Citrus Fruits Easier to Squeeze", "watch?v=XxKv-IApgHQ", 0),
    (26, 1, "How to Tie a Roast With a String", "watch?v=ND53rqGd28s", 0),
    (27, 1, "How to Cut Tomatoes", "watch?v=2wEesa3jMiM", 0),
    (28, 1, "How to Mince Walnuts", "watch?v=dpEtwVUU0KY", 0),
    (29, 1, "How to Melt Chocolate", "watch?v=CQJp-ZqMvBE", 0),
    (30, 1, "How to Cook Roasted Garlic", "watch?v=t9B3zKWs7cU", 0),
    (31, 1, "How to Caramelise Onions", "watch?v=Nh7V3Qj-9lU", 0),
    (32, 1, "How to Clean Chicken Legs from Joints", "watch?v=-1sj9uFZsyA", 0),
    (33, 1, "How to Peel and Chop Hazelnuts", "watch?v=UHHYf33oqig", 0),
    (34, 1, "How to Peel Avocado", "watch?v=6etDV96Tjbw", 0),
    (35, 1, "How to Cut Fennel", "watch?v=gtGYWZLskCo", 0),
    (36, 1, "How to Carve a Turkey", "watch?v=w-AgOnli4Hc", 0),
    (37, 1, "How to Stuff a Turkey", "watch?v=voWVwYOpLyw", 0),
    (38, 1, "How to Cook Classic Sweet Shortcrust Pastry", "watch?v=c91hBdZbnwQ", 0),
    -- cookingguide youtube channel
    (39, 2, "How to Clean Artichokes", "watch?v=rAF3o5rITy8", 0),
    (40, 2, "How to Slice Apples", "watch?v=65p7wk-hgEQ", 0),
    (41, 2, "How to Cut Zucchinis", "watch?v=6pjLeHMWnS4", 0),
    (42, 2, "How to Mash Bananas", "watch?v=EfmQfQWK7SU", 0),
    (43, 2, "How to Crack Eggs", "watch?v=PF7dKy7FNtg", 0),
    (44, 2, "How to Beat Eggs", "watch?v=3H8hxFlCcCQ", 0),
    (45, 2, "How to Peel Peaches", "watch?v=NO4t5oA-EUM", 0),
    (46, 2, "How to Chop Rosemary", "watch?v=c80C0hSxa2Y", 0),
    (47, 2, "How to Use a Cooking String", "watch?v=gGDjT0zPM10", 0),
    (48, 2, "How to Use a Colander", "watch?v=wdLA40yskjg", 0),
    (49, 2, "How to Chop Italian Parsely", "watch?v=xpBT9v8GAF8", 0),
    (50, 3, "How to Pick Bananas", "watch?v=yMByZrRbU68", 0),
    (51, 3, "How to Chop Apples", "watch?v=yacwMfbxssw", 0),
    (52, 3, "How to Pick Blueberries", "watch?v=4sgOglJPXL4", 0),
    (53, 3, "How to Pick Italian Parsely", "watch?v=676tQLenltw", 0),
    (54, 3, "How to Use a Deboner", "watch?v=AwCmx5yUCQk", 0),
    (55, 3, "How to Peel Pineapples", "watch?v=D1dQ0h-X5YU", 0),
    (56, 3, "How to Use a Bread Knife", "watch?v=GjArbq8xDWc", 0),
    (57, 3, "How to Core Pineapples", "watch?v=NBrBzzwxHgI", 0),
    (58, 3, "How to Slice Red Pears", "watch?v=TkDafHALFVg", 0),
    (59, 3, "How to Use a Bamboo Steamer", "watch?v=U_RkcOof098", 0),
    (60, 3, "How to Core Apples", "watch?v=ZIvr9Ex59ug", 0),
    (61, 3, "How to pick Thyme", "watch?v=_IWtr4bUlrM", 0),
    (62, 3, "How to Dice Zucchini", "watch?v=byb91Ju0UJw", 0),
    (63, 3, "How to Broil Seafood", "watch?v=dI8op-WFQvM", 0),
    (64, 3, "How to Make Whipped Cream", "watch?v=f2fFcjwvTWs", 0),
    (65, 3, "How to Slice Pineapples", "watch?v=jbd6iqS89oM", 0),
    (66, 3, "How to Cube Turnips", "watch?v=lkXqH_BqIfU", 0),
    (67, 4, "How to Whip Egg Whites", "watch?v=pbbH_jlqlBk", 0),
    (68, 4, "How to Use a Cleaver Knife", "watch?v=rT6vSieNcC0", 0),
    (69, 4, "How to Grate Ginger Root", "watch?v=-abiTYqbPQM", 0),
    (70, 4, "How to Peel Tomatoes", "watch?v=1GQ0r-5ufC4", 0),
    (71, 4, "How to Pick Ginger Root", "watch?v=6TQfU1J8fN8", 0),
    (72, 4, "How to Slice Turnips", "watch?v=AbLWARpORLs", 0),
    (73, 4, "How to Poach Seafood", "watch?v=IYRN0MEX_xg", 0),
    (74, 4, "How to Pick Lemongrass", "watch?v=K43dkE7M4iE", 0),
    (75, 4, "How to Flambe", "watch?v=Lq4GjyCisbI", 0),
    (76, 4, "How to Pick Turnips", "watch?v=VT2EGiZhcqw", 0),
    (77, 4, "How to Pick and Types Tofu", "watch?v=_YDgOf-s4ho", 0),
    (78, 4, "How to Halve a Banana", "watch?v=dWv6LC_0uSw", 0),
    (79, 5, "How to Slice Tofu", "watch?v=e9VyoziVC7c", 0),
    (80, 5, "How to Pick Blackberries", "watch?v=mPPO7Zv421U", 0),
    (81, 5, "How to Thaw Fish", "watch?v=qGChFQyYTDo", 0),
    (82, 5, "How to Bake Seafood", "watch?v=DYi5_vXrz6o", 0),
    (83, 5, "How to Clean Turnips", "watch?v=c9wFgwOeb9o", 0),
    (84, 5, "How to Clean Ginger Root", "watch?v=jkowzIV2QqI", 0),
    (85, 5, "How to Pan Fry Bacon", "watch?v=n3f4GOEv7ck", 0),
    (86, 5, "How to Marinate Tofu", "watch?v=yPh81Q9DgZA", 0),
    (87, 5, "How to Use a Deep Fryer", "watch?v=-7zDfKNEkmY", 0),
    (88, 5, "How to Select a Whole Chicken", "watch?v=1_NuuC2uMBo", 0),
    (89, 5, "How to Pick Calamari", "watch?v=2z1E1sILbVg", 0),
    (90, 5, "How to Pick Pork Tenderloin", "watch?v=3BGaZl9DpCo", 0),
    (91, 5, "How to Dice Capsicum", "watch?v=3hULyHM3cGo", 0),
    (92, 5, "How to Sear Chicken", "watch?v=4IJorho8zGc", 0),
    (93, 5, "How to Use Chicken Safely", "watch?v=4pCI8BIVvfk", 0),
    (94, 5, "How to Clean Capsicum", "watch?v=5oxepN3X89U", 0),
    (95, 5, "How to Chop Hazelnuts", "watch?v=BbYa3Bu0VWk", 0),
    (96, 6, "How to Pick Octopus", "watch?v=CBrvIUamD0o", 0),
    (97, 6, "How to Microwave Bacon", "watch?v=FQi2-EvpNiw", 0),
    (98, 6, "How to Chop Walnuts", "watch?v=HAUtd6atcr8", 0),
    (99, 6, "How to Baste Ham", "watch?v=IbyHWarJ8vQ", 0),
    (100, 6, "How to Pick Hazelnuts", "watch?v=Kb-sG39ckFs", 0),
    (101, 6, "How to Pick Bok Choy", "watch?v=LEvyc_0-VeY", 0),
    (102, 6, "How to Trim Fat from Pork Tenderloin", "watch?v=LFVYcfyd_S8", 0),
    (103, 6, "How to Clean Bok Choy", "watch?v=LLZTvu9N_DU", 0),
    (104, 6, "How to Chop Chestnus", "watch?v=MGS21XX3X7c", 0),
    (105, 6, "How to Pick Ham", "watch?v=Ml53GhNt6hg", 0),
    (106, 6, "How to Butterfly Chicken Breast", "watch?v=Ot46Cueod4s", 0),
    (107, 6, "How to Clean Broccoli", "watch?v=Q2kZAEU5RRU", 0),
    (108, 6, "How to Pan Fry Chicken", "watch?v=QFZ-OaiB3nY", 0),
    (109, 6, "How to Chop Peacans", "watch?v=QWyBkwzsE6g", 0),
    (110, 6, "How to Pick Mussels", "watch?v=SQZMMTOGeOI", 0),
    (111, 6, "How to Pick Pecans", "watch?v=T6TEBglwJh0", 0),
    (112, 6, "How to Broil Chicken Thighs", "watch?v=V3nTtHja8JQ", 0),
    (113, 6, "How to Use a Cheese Slicer", "watch?v=VO5SRS5DTO8", 0),
    (114, 6, "How to Pick Pistachio Nuts", "watch?v=WbxkXGkl7QY", 0),
    (115, 6, "How to Make Al Dente Pasta", "watch?v=ZuQcQOSXpe0", 0),
    (116, 6, "How to Pick Bacon", "watch?v=_h1j8yIayuI", 0),
    (117, 6, "How to Pick Pine Nuts", "watch?v=axCT96sGwnA", 0),
    (118, 7, "How to Sear Pork Tenderloin", "watch?v=gweiQjiaUPk", 0),
    (119, 7, "How to Pick Macadamia Nuts", "watch?v=i_Ls5pi7pP0", 0),
    (120, 7, "How to Quarter a Whole Chicken", "watch?v=id92bIP9Wm4", 0),
    (121, 7, "How to Cook Safely With Fish", "watch?v=jSkJlDAzWVg", 0),
    (122, 7, "How to Pick Broccoli", "watch?v=juKP3khVF78", 0),
    (123, 7, "How to Chop Macadamia Nuts", "watch?v=oHW_tUsw2zQ", 0),
    (124, 7, "How to Chop Peanuts", "watch?v=omy0L_U82xs", 0),
    (125, 7, "How to Cook Cous Cous", "watch?v=osywU2_1fAk", 0),
    (126, 7, "How to Cool White Rice", "watch?v=oxsJXH-VKmg", 0),
    (127, 7, "How to Roast Capsicum", "watch?v=rQ1_HJtRmO0", 0),
    (128, 7, "How to Pick Peanuts", "watch?v=yJbn5rbUGp8", 0),
    (129, 7, "How to Slice Strawberries", "watch?v=OvAHmLw5e5Q", 0),
    (130, 7, "How to Pick Cashews", "watch?v=STi0bt3SBjM", 0),
    (131, 7, "How to Slice Thai Chilli Peppers", "watch?v=ZIcnGkovCvY", 0),
    (132, 7, "How to Oven Roast Chicken", "watch?v=czGlKhaqMQ8", 0),
    (133, 7, "How to Pick Walnuts", "watch?v=g8voWo7V8B4", 0),
    (134, 7, "How to Clean White Button Mushrooms", "watch?v=jGyZVAuCL54", 0),
    (135, 7, "How to Chop Brazil Nuts", "watch?v=vJ5modStrn4", 0),
    (136, 7, "How to Pick Chestnuts", "watch?v=01cYXYmipUY", 0),
    (137, 7, "How to Dice Jalapeno Peppers", "watch?v=0dbpF2BghI0", 0),
    (138, 8, "How to Pick Clams", "watch?v=3mxnA38Xqhw", 0),
    (139, 8, "How to Clean Watermelons", "watch?v=3wYFJLap3dU", 0),
    (140, 8, "How to Steam Clams", "watch?v=4IScX7YvnqU", 0),
    (141, 8, "How to Use a Dry Measuring Cup", "watch?v=7gFLl6SR9Ys", 0),
    (142, 8, "How to Cross Brussel Sprouts", "watch?v=ADHJkGY7qXM", 0),
    (143, 8, "How to Steep Chamomile", "watch?v=EgQ63WD4nRA", 0),
    (144, 8, "How to Bread Products", "watch?v=EzF6Eaga8Pw", 0),
    (145, 8, "How to Pick Strawberries", "watch?v=FEdGrbDhZBo", 0),
    (146, 8, "How to Slice Starfruits", "watch?v=Hcgv0smgSXg", 0),
    (147, 8, "How to Prepare Calamari", "watch?v=IREOfCKkSu4", 0),
    (148, 8, "How to Pick Raspberries", "watch?v=JVzGkRl8df8", 0),
    (149, 8, "How to Use Parchment Paper", "watch?v=Jz4Lr9jGKkk", 0),
    (150, 8, "How to Use a Measuring Sppon", "watch?v=NdNRZL304gg", 0),
    (151, 8, "How to Clean Green Cabbage", "watch?v=O74sngXTumk", 0),
    (152, 8, "How to Pick Shitake Mushrooms", "watch?v=P0V01pXu3vY", 0),
    (153, 8, "How to Pick Almonds", "watch?v=QRdBrAwnVnM", 0),
    (154, 8, "How to Pick Brussel Sprouts", "watch?v=Rxz_iyHt7NY", 0),
    (155, 9, "How to Cube Watermelons", "watch?v=VJ_nRtuX3Mw", 0),
    (156, 9, "How to Use a Liquid Measuring Cup", "watch?v=XvYTYREiFZU", 0),
    (157, 9, "How to Chop Cashews", "watch?v=Y-VpXlrn-uM", 0),
    (158, 9, "How to Chop Strawberries", "watch?v=ZYiXRX6Fmdc", 0),
    (159, 9, "How to Chop Almonds", "watch?v=_AxlGCTlmGc", 0),
    (160, 9, "How to Select Veal", "watch?v=cq4v-pwy91w", 0),
    (161, 9, "How to Use a Flavour Injector", "watch?v=dRQuW4eizM0", 0),
    (162, 9, "How to Make Oven Toasted Almonds", "watch?v=eWMdUSudgrA", 0),
    (163, 9, "How to Lice Watermelons", "watch?v=gCsgTNillW4", 0),
    (164, 9, "How to Slice Green Cabbage", "watch?v=iTXx6NLKlTY", 0),
    (165, 9, "How to Fan Strawberries", "watch?v=mma4wgX22wg", 0),
    (166, 9, "How to Clean Brussel Sprouts", "watch?v=q3dvqyHSAEA", 0),
    (167, 9, "How to Use an Immersion Blender", "watch?v=t9GmitshuZg", 0),
    (168, 9, "How to Use a Hand Mixer", "watch?v=tMPIkdO_3SY", 0),
    (169, 9, "How to Pick Parsely", "watch?v=-kvHYerNVqg", 0),
    (170, 9, "How to Cube Pineapples", "watch?v=1OB-XqLTntY", 0),
    (171, 9, "How to Use a Ladle", "watch?v=3AZ6tKJhKgg", 0),
    (172, 9, "How to Use a Paring Knife", "watch?v=7dieSXpQdEo", 0),
    (173, 9, "How to Steam Vegetables", "watch?v=AOOh9SyKhc4", 0),
    (174, 9, "How to Pick Eggs", "watch?v=Bw8YTe4aXKY", 0),
    (175, 9, "How to Clean Zucchini", "watch?v=E3U1zKfLyNQ", 0),
    (176, 9, "How to Use a Zester", "watch?v=HfEqvpFF0F8", 0),
    (177, 10, "How to Pit Plums", "watch?v=HyNVL8nQCTw", 0),
    (178, 10, "How to Use a Rolling Pin", "watch?v=JPc9sEHUNes", 0),
    (179, 10, "How to Boil Crab Legs", "watch?v=NlmTOFjtPpQ", 0),
    (180, 10, "How to Use a Garlic Press", "watch?v=Qud3NrN7fDY", 0),
    (181, 10, "How to Slice Zucchini", "watch?v=RoqP1J0Y6AY", 0),
    (182, 10, "How to Pick Chipotle Peppers", "watch?v=VVVQRNl6-os", 0),
    (183, 10, "How to Saute in a Wok", "watch?v=ZV0V9bc31U8", 0),
    (184, 10, "How to Pick Oregano", "watch?v=au6Ki6FpyDY", 0),
    (185, 10, "How to Cube Plums", "watch?v=bIne0PO8cq4", 0),
    (186, 10, "How to Soft Boil Eggs", "watch?v=cCPR3l_iEgA", 0),
    (187, 10, "How to Flip Food in a Wok", "watch?v=cNaiCF5fmM4", 0),
    (188, 10, "How to Use a Pan", "watch?v=dNHjY3cxbSI", 0),
    (189, 10, "How to Pick Watermelons", "watch?v=e-yKAmyyOPc", 0),
    (190, 10, "How to Use an Iron Skillet", "watch?v=f3MvWRFKTZY", 0),
    (191, 10, "How to Use a Stand Mixer", "watch?v=pkTe65K7o90", 0),
    (192, 10, "How to Use a Lemon Press", "watch?v=u3HfFW8oFe8", 0),
    (193, 10, "How to Use a Masher", "watch?v=zY_412Mp4Xs", 0),
    (194, 10, "How to Shave Parmesan Cheese", "watch?v=zuKODO8tLZM", 0),
    (195, 10, "How to Pick Cinnamon", "watch?v=3605Pg2vrP4", 0),
    (196, 10, "How to Boil Spinach", "watch?v=7Sy1ZgmmZc8", 0),
    (197, 10, "How to Use a Stock Pot", "watch?v=8kDCuWqK7JI", 0),
    (198, 11, "How to Use a Strainer", "watch?v=9qq3TyElMwo", 0),
    (199, 11, "How to Use Kitchen Scissors", "watch?v=J5I9wAQoizM", 0),
    (200, 11, "How to Pick Artichokes", "watch?v=N7hsggFsESk", 0),
    (201, 11, "How to Clean Portobello Mushrooms", "watch?v=RQr_EdvnyQg", 0),
    (202, 11, "How to Clean White Asparagus", "watch?v=U-qlxcbw56Y", 0),
    (203, 11, "How to Cut Beef Against Grain", "watch?v=YOnkygi99Pg", 0),
    (204, 11, "How to Use a Spatula", "watch?v=Z4l9UYphgDY", 0),
    (205, 11, "How to Grate Cinnamon", "watch?v=e32Rv6WnU-E", 0),
    (206, 11, "How to Pan Fry", "watch?v=fLxvuFj7r2Q", 0),
    (207, 11, "How to Use a Steak Knife", "watch?v=fxSzH73AMVk", 0),
    (208, 11, "How to Soften Butter", "watch?v=olUyDOsCNMs", 0),
    (209, 11, "How to Clean Artichokes", "watch?v=rAF3o5rITy8", 0),
    (210, 11, "How to Boil Artichokes", "watch?v=rqCxJN1FumQ", 0),
    (211, 11, "How to Pick Apples", "watch?v=gk1u8nDtpo8", 0),
    (212, 11, "How to Shred Cheddar Cheese", "watch?v=nRyf4VWEsDY", 0),
    (213, 11, "How to Slice Avocados", "watch?v=0LqJdMxZras", 0),
    (214, 11, "How to Saute Onions", "watch?v=2NKDdgHLp8U", 0),
    (215, 11, "How to Peel Carrots", "watch?v=4LRZ5-GbUOU", 0),
    (216, 12, "How to Use a Steamer", "watch?v=5wdDqjqDn80", 0),
    (217, 12, "How to Dice Shallots", "watch?v=9bgacGJsmpU", 0),
    (218, 12, "How to Saute Vegetables", "watch?v=AEUzh49ZiSM", 0),
    (219, 12, "How to Prepare Watercress", "watch?v=CPzqkQ8-6SY", 0),
    (220, 12, "How to Dice Avocados", "watch?v=CYx6lO0suuU", 0),
    (221, 12, "How to Pit Avocados", "watch?v=F6jHrCgwcwg", 0),
    (222, 12, "How to Pick Asparagus", "watch?v=G5wYzz06FLw", 0),
    (223, 12, "How to Peel Apples", "watch?v=GFZ2SEhD5DY", 0),
    (224, 12, "How to Clean Raddishes", "watch?v=HlLWIXrDhr8", 0),
    (225, 12, "How to Check Doneness When Baking", "watch?v=ILVLKeMImiw", 0),
    (226, 12, "How to Clean Carrots", "watch?v=JSL2ETSU9QY", 0),
    (227, 12, "How to Chop Mint", "watch?v=O4xuBMWPF_w", 0),
    (228, 12, "How to Clean Cauliflower", "watch?v=Qj90HckZbdQ", 0),
    (229, 12, "How to Use a Vegetable Peeler", "watch?v=RcS6SbX-0Bg", 0),
    (230, 12, "How to Chop Chocolate", "watch?v=Sco8k6FmBLY", 0),
    (231, 12, "How to Use a Whisk", "watch?v=UuajCIKaVGE", 0),
    (232, 12, "How to Slice Rhubarb", "watch?v=VSdwivdjxzk", 0),
    (233, 12, "How to Pick Chives", "watch?v=W8Y6AKg6Bto", 0),
    (234, 12, "How to Deep Fry Tofu", "watch?v=XUv5mZk832s", 0),
    (235, 12, "How to Pan Fry Tofu", "watch?v=XiJlWncaLLI", 0),
    (236, 13, "How to Pick Bay Leaves", "watch?v=aoM4gungTv4", 0),
    (237, 13, "How to Use a Wok", "watch?v=c-hD20fatdM", 0),
    (238, 13, "How to Chop Chives", "watch?v=fUBdCoby-20", 0),
    (239, 13, "How to Use Tongs", "watch?v=gNdKUJt_3ts", 0),
    (240, 13, "How to Sift Flour", "watch?v=rWRHKX-9C6c", 0),
    (241, 13, "How to Boil Beets", "watch?v=rcUWky400UM", 0),
    (242, 13, "How to Prepare Spaghetti Squash", "watch?v=sD-4E_woLz0", 0),
    (243, 13, "How to Pick Bean Sprouts", "watch?v=sDmh5fqjaIA", 0),
    (244, 13, "How to Slice Mozzarella Cheese", "watch?v=umDlYLAgxVM", 0),
    (245, 13, "How to Sweat Onions", "watch?v=vK0zLJy3hnY", 0),
    (246, 13, "How to Slice Radishes", "watch?v=wdNcXafZFJ4", 0),
    (247, 13, "How to Pick Salmon", "watch?v=0YIg_gZCAas", 0),
    (248, 13, "How to Slice Fennel", "watch?v=1q05rz0_uUA", 0),
    (249, 13, "How to Pick Bone in Ribeye", "watch?v=3GUgi1bF6ow", 0),
    (250, 13, "How to Prepare Butternut Squash", "watch?v=3qwTjTUMT8Y", 0),
    (251, 13, "How to Peel Pears", "watch?v=46v6oMSOfi0", 0),
    (252, 13, "How to Blanch Green Beans", "watch?v=AYHPPa2H8yM", 0),
    (253, 13, "How to Pick Sun Dried Tomatoes", "watch?v=BV8gDHHSRRg", 0),
    (254, 13, "How to Pick Red Snapper", "watch?v=G0T0XBDj8qw", 0),
    (255, 13, "How to Pick Sugar Snap Peas", "watch?v=GgYFN3tUthg", 0),
    (256, 13, "How to Shred Carrots", "watch?v=NEKiIzfxFvc", 0),
    (257, 13, "How to Pick Alfalfa Sprouts", "watch?v=WLqc4Q3ZuS4", 0),
    (258, 14, "How to Pick Basil", "watch?v=XXcCfeLjmDs", 0),
    (259, 14, "How to Clean Green Beans", "watch?v=c-tzXjBQ2tU", 0),
    (260, 14, "How to Slice White Potatoes", "watch?v=hg1gQPRGyrM", 0),
    (261, 14, "How to Clean Celery", "watch?v=k_7DOLxvrbM", 0),
    (262, 14, "How to Pan Fry Tempeh", "watch?v=l-_yLgqa-YQ", 0),
    (263, 14, "How to Make an Icing Bag", "watch?v=lHHv22G8ixo", 0),
    (264, 14, "How to Caramelize Sugar", "watch?v=pIOBaqKkCi8", 0),
    (265, 14, "How to Sear Tuna Steak", "watch?v=qXBfYYF-BGA", 0),
    (266, 14, "How to Core Pears", "watch?v=r3gPZ7gY6jA", 0),
    (267, 15, "How to Pick Snap Peas", "watch?v=w0D-cqychuU", 0),
    (268, 15, "How to Shred Iceberg Lettuce", "watch?v=NQ7uk3aOxtE", 0),
    (269, 15, "How to Scramble Eggs", "watch?v=_8BJZetE9rg", 0),
    (270, 15, "How to Poach Eggs", "watch?v=d9XTJ9-_n0Q", 0),
    (271, 15, "How to Grill a Hamburger", "watch?v=hME_epnyrYM", 0),
    (272, 15, "How to Peel White Potatoes", "watch?v=qeD7LJKwauw", 0),
    (273, 15, "How to Pick Spinach", "watch?v=CorR1aCpf3A", 0),
    (274, 15, "How to Pick Purple Eggplant", "watch?v=MwFfU4ZODu4", 0),
    (275, 15, "How to Boil Edamame (Soy Beans)", "watch?v=_gfc_EQ-lOQ", 0),
    (276, 15, "How to Flip Eggs", "watch?v=3DriNZTCXxQ", 0),
    (277, 15, "How to Brown Butter", "watch?v=CBiByrMgCMc", 0),
    (278, 15, "How to Slice Leek", "watch?v=Dz-igwuwhFc", 0),
    (279, 15, "How to Clarify Butter", "watch?v=FPHXZTYi2Ow", 0),
    (280, 15, "How to Grill Sirloin", "watch?v=KFH9y-bAz4M", 0),
    (281, 16, "How to Slice Sweet Potatoes", "watch?v=LYOofLe64IA", 0),
    (282, 16, "How to Grill Tofu", "watch?v=VeVG2OPw6aw", 0),
    (283, 16, "How to Pick Ribeye Steaks", "watch?v=XMZZbhmWetk", 0),
    (284, 16, "How to Boil Eggs", "watch?v=a9fVMm3bHYs", 0),
    (285, 16, "How to Fry Eggs", "watch?v=j2C-bp7I1jU", 0),
    (286, 16, "How to Pick Green Leaf Lettuce", "watch?v=kiKJzHyP5Yo", 0),
    (287, 16, "How to Peel Sweet Potatoes", "watch?v=oB6h3DscMUw", 0),
    (288, 16, "How to Clean Iceberg Lettuce", "watch?v=tAxuaJyPqhA", 0),
    (289, 16, "How to Punch Out Dough", "watch?v=8InH3VJP71E", 0),
    (290, 16, "How to Pick Cherry Tomatoes", "watch?v=G7ZXu8Sea9k", 0),
    (291, 16, "How to Mince Garlic", "watch?v=HFPhXM6TtI4", 0),
    (292, 17, "How to Pick Tuna Steak", "watch?v=JsD3dwdYjGM", 0),
    (293, 17, "How to Knead Dought", "watch?v=KvCAteRyhAQ", 0),
    (294, 17, "How to Prepare Potstickers for Cooking", "watch?v=NsE294KL8EY", 0),
    (295, 17, "How to Use the Grill Lid Properly", "watch?v=Yt0Vze7UITs", 0),
    (296, 17, "How to Simmer Water", "watch?v=e_hKjQXvA1Q", 0),
    (297, 17, "How to Melt Chocolate", "watch?v=g1076D4xR84", 0),
    (298, 17, "How to Grill Onions", "watch?v=gsZK6BTnk3k", 0),
    (299, 17, "How to How to Use a Meat Thermometer", "watch?v=iTwRyl_rj6s", 0),
    (300, 17, "How to Pick Garlic", "watch?v=01w1cacfiS0", 0),
    (301, 17, "How to Remove Kernels from Corn", "watch?v=0KZcl4D63gk", 0),
    (302, 17, "How to Pick Prawns", "watch?v=3iJQB94kuNQ", 0),
    (303, 17, "How to Use Oil When Grilling", "watch?v=7P0YYT2JtlY", 0),
    (304, 17, "How to Brown Ground Beef", "watch?v=ACW08JyDuVg", 0),
    (305, 17, "How to Steam Vegetables", "watch?v=ASasVFiKF1M", 0),
    (306, 17, "How to Grill Potatoes", "watch?v=AnmkJJBHSw4", 0),
    (307, 17, "How to Press Garlic", "watch?v=C5-LGqwPnhY", 0),
    (308, 17, "How to Pick Green Onions", "watch?v=CA-HgJQMmJg", 0),
    (309, 17, "How to Grill Corn", "watch?v=CHijvLqiub4", 0),
    (310, 18, "How to Slice Cucumbers", "watch?v=Ep8qi0yQ7wE", 0),
    (311, 18, "How to Pick Kale", "watch?v=MWD0I-NZZ5o", 0),
    (312, 18, "How to Remove Fat from Pork Chops", "watch?v=Q5myb1MFfWA", 0),
    (313, 18, "How to Slice Chinese Eggplant", "watch?v=W4NARYbsEtI", 0),
    (314, 18, "How to Slice Tomatoes", "watch?v=YlkC80JFyds", 0),
    (315, 18, "How to Break Down a Lobster", "watch?v=alFmgjE5wvk", 0),
    (316, 18, "How to Pour Pancake Batter", "watch?v=bf49gfkamMY", 0),
    (317, 18, "How to Slice Green Onions", "watch?v=dcdhaxl54pY", 0),
    (318, 18, "How to Tie Roast Meat", "watch?v=hpEvYqmynuM", 0),
    (319, 18, "How to Pick Cucumbers", "watch?v=ito9_Qx-W14", 0),
    (320, 18, "How to Grill Safely", "watch?v=l0rjakMlfFA", 0),
    (321, 18, "How to Fold Omelets", "watch?v=n9YZZR0y128", 0),
    (322, 18, "How to Roast Meat", "watch?v=pWBnpU7Y7Qw", 0),
    (323, 18, "How to Crush Garlic", "watch?v=uoYYX_SpV7I", 0),
    (324, 18, "How to Flip Pancakes", "watch?v=yCbhuGyFev4", 0),
    (325, 18, "How to Slice Cucumbers", "watch?v=yLMduj1YfoY", 0),
    (326, 18, "How to Prepare Kale", "watch?v=yX9d9OPmtB8", 0),
    (327, 18, "How to Grill Zuchinni", "watch?v=zE3ht4tWGwo", 0),
    (328, 18, "How to Mince Red Onions", "watch?v=0ZONIYnX03k", 0),
    (329, 19, "How to Boil Tripe", "watch?v=4auPt4nf984", 0),
    (330, 19, "How to Boil Beef Tongue", "watch?v=4egkJdL8WWE", 0),
    (331, 19, "How to Sear Beef", "watch?v=AKN-UZV9atE", 0),
    (332, 19, "How to Pick Corn", "watch?v=Am_KLxhZkG0", 0),
    (333, 19, "How to Pick Lamb Chops", "watch?v=BalNsWI1sCQ", 0),
    (334, 19, "How to Grill Fish", "watch?v=CxKq3FUvXeI", 0),
    (335, 19, "How to Marinade Chicken", "watch?v=Gh2I_4VojmI", 0),
    (336, 19, "How to Slice Garlic", "watch?v=HOKxWHPmVKY", 0),
    (337, 19, "How to Blanch Vegetables", "watch?v=ZzEDraqcqMw", 0),
    (338, 19, "How to Dice Red Onions", "watch?v=mZCuba7tBZI", 0),
    (339, 19, "How to Peel Garlic", "watch?v=rEJbfJlkfCs", 0),
    (340, 19, "How to Pick Cucumbers", "watch?v=vetqiH05Q90", 0),
    (341, 19, "How to Peel Grapes", "watch?v=-ZP0PD6caJE", 0),
    (342, 19, "How to Toast Macadamia Nuts", "watch?v=W4RA4t7pvCU", 0),
    (343, 19, "How to Freeze Strawberries", "watch?v=a64JJgEL6es", 0),
    (344, 19, "How to Roast Pumpkin Seeds", "watch?v=loGdPINQ93E", 0)
"""
cursor.execute(insert_skillVideos_query)
conn.commit()


# insert into skillVideoInRecipe
delete_query = """DELETE FROM skillVideoInRecipe WHERE 1"""
cursor.execute(delete_query)
insert_skillVideoInRecipe_query = """
INSERT INTO 
    skillVideoInRecipe (recipe_id, skill_video_id)
VALUES
    (2, 1),
    (0, 2),
    -- random
    (0, 5),
    (1, 3)
"""
cursor.execute(insert_skillVideoInRecipe_query)
conn.commit()

# insert into skillVideoSaves
delete_query = """DELETE FROM skillVideoSaves WHERE 1"""
cursor.execute(delete_query)

insert_skillVideoSaves_query = """
INSERT INTO 
    skillVideoSaves(ruser_id, skill_video_id)
VALUES
    (0, 1),
    (0, 2),
    (0, 5),
    (0, 3)
"""
cursor.execute(insert_skillVideoSaves_query)
conn.commit()

cursor.close()